modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="dmadditions"
version="${file.jarVersion}"
displayName="Dalek Mod Additions"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/dalek-mod-additions"
displayURL="https://discord.gg/P6SstpZsjX"
logoFile="logo.png"
credits="1JamesLeDolphin, SamTiz, Torchwood_one, TheMajorNoob_239"
authors="QRT Studios"
description='''Adds various things, and changes different features of The Dalek Mod'''

[[dependencies.dmadditions]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dmadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dmadditions]]
modId="dalekmod"
mandatory=true
versionRange="[65.1.1, )"
ordering="NONE"
side="BOTH"
